In [330]:
"""Classes."""

'Classes.'

## Классы и объекты в Питоне

### Создание класса

#### Создание класса и метод `.__init__()`

In [ ]:
# создадим класс CatClass
# нашему классу понадобится Numpy
# массивом Numpy и другими объектами
# fmt: off
import numpy as np
# из набора линейных моделей библиотеки sklearn импортируем линейную регрессию
from sklearn.linear_model import LinearRegression


class CatClass:
    """Basic cat class."""

    def __init__(self) -> None:
        """Initialize empty cat instance."""
        pass  # pylint: disable=unnecessary-pass

#### Создание объекта

In [332]:
# создадим объект Matroskin класса CatClass
Matroskin = CatClass()

# проверим тип данных созданной переменной
type(Matroskin)

__main__.CatClass

#### Атрибуты класса

In [333]:
# вновь создадим класс CatClass


class CatClass2:
    """Class representing a cat with color and type attributes."""

    def __init__(self, color: str) -> None:
        """Initialize cat with given color."""
        # этот параметр будет записан в переменную атрибута self.color
        self.color: str = color

        # значение атрибута type_ задается внутри класса
        self.type_: str = "cat"

In [334]:
# повторно создадим объект класса CatClass, передав ему параметр цвета шерсти
Matroskin2 = CatClass2("gray")

# и выведем атрибуты класса
print(Matroskin2.color, Matroskin2.type_)

gray cat


#### Методы класса

In [335]:
# перепишем класс CatClass


class CatClass3:
    """A class representing a cat with color and type."""

    # метод .__init__() и атрибуты оставим без изменений
    def __init__(self, color: str) -> None:
        """Initialize cat with given color."""
        self.color = color
        self.type_ = "cat"

    # однако добавим метод, который позволит коту мяукать
    def meow(self) -> None:
        """Make the cat meow three times."""
        for _ in range(3):
            print("Мяу")

    # и метод .info() для вывода информации об объекте
    def info(self) -> None:
        """Print the cat's color and type."""
        print(self.color, self.type_)

In [336]:
# создадим объект
Matroskin3 = CatClass3("gray")

In [337]:
# применим метод .meow()
Matroskin3.meow()

Мяу
Мяу
Мяу


In [338]:
# и метод .info()
Matroskin3.info()

gray cat


### Принципы ООП

#### Инкапсуляция

In [339]:
# изменим атрибут type_ объекта Matroskin на dog
Matroskin3.type_ = "dog"

# выведем этот атрибут
Matroskin3.type_

'dog'

In [340]:
class CatClass4:
    """A cat with color and type."""

    def __init__(self, color: str) -> None:
        """Initialize cat with color."""
        self.color = color
        # символ подчеркивания ПЕРЕД названием атрибута указывает,
        # что это частный атрибут и изменять его не стоит
        self._type_: str = "cat"

In [341]:
# вновь создадим объект класса CatClass
Matroskin4 = CatClass4("gray")

# и изменим значение атрибута _type_
# Matroskin4._type_ = "dog"
# Matroskin4._type_

In [342]:
class CatClass5:
    """A cat with color and protected type."""

    def __init__(self, color: str) -> None:
        """Initialize cat with color."""
        self.color = color
        # символ двойного подчеркивания предотвратит доступ извне
        # self.__type_: str = "cat"

In [343]:
# при попытке вызова такого атрибута Питон выдаст ошибку
Matroskin5 = CatClass5("gray")
# Matroskin5.__type_

In [344]:
# поставим _CatClass перед __type_
# Matroskin5._CatClass__type_ = "dog"

# к сожалению, значение атрибута изменится
# Matroskin5._CatClass__type_

#### Наследование классов

Создание родительского класса и класса-потомка

In [345]:
# создадим класс Animal


class Animal:
    """Animal with weight and length."""

    # пропишем метод .__init__() с двумя параметрами: вес (кг) и длина (см)
    def __init__(self, weight: float, length: float) -> None:
        """Initialize animal with weight and length."""
        # поместим аргументы этих параметров в соответствующие переменные
        self.weight = weight
        self.length = length

    # объявим методы .eat()
    def eat(self) -> None:
        """Make animal eat."""
        print("Eating")

    # и .sleep()
    def sleep(self) -> None:
        """Make animal sleep."""
        print("Sleeping")

In [346]:
# создадим класс Bird
# родительский класс Animal пропишем в скобках


class Bird(Animal):
    """Bird that can fly."""

    # внутри класса Bird объявим новый метод .move()
    def move(self) -> None:
        """Make bird fly."""
        # для птиц .move() будет означать "летать"
        print("Flying")

In [347]:
# создадим объект pigeon и передадим ему значения веса и длины
pigeon = Bird(0.3, 30)

In [348]:
# посмотрим на унаследованные у класса Animal атрибуты
print(pigeon.weight, pigeon.length)

0.3 30


In [349]:
# и методы
pigeon.eat()

Eating


In [350]:
# теперь вызовем метод, свойственный только классу Bird
pigeon.move()

Flying


Функция `super()`

In [351]:
# снова создадим класс Bird


class Bird1(Animal):
    """Bird class with flying capability."""

    # в метод .__init__() добавим параметр скорости полета (км/ч)
    def __init__(self, weight: float, length: float, speed: float) -> None:
        """Initialize bird with weight, length and flying speed."""
        # с помощью super() вызовем метод .__init__() род. класса Animal
        super().__init__(weight, length)
        self.flying_speed = speed

    # вновь пропишем метод .move()
    def move(self) -> None:
        """Make bird fly."""
        print("Flying")

In [352]:
# вновь создадим объект pigeon класса Bird, но уже с тремя параметрами
pigeon2 = Bird1(0.3, 30, 100)

In [353]:
# вызовем как унаследованные, так и собственные атрибуты класса Bird
print(pigeon2.weight, pigeon2.length, pigeon2.flying_speed)

0.3 30 100


In [354]:
# вызовем унаследованный метод .sleep()
pigeon2.sleep()

Sleeping


In [355]:
# и собственный метод .move()
pigeon2.move()

Flying


Переопределение класса

In [ ]:
# создадим подкласс Flightless класса Bird


class Flightless(Bird):
    """Flightless bird class that can only run."""

    # метод .__init__() этого подкласса "стирает" .__init__() род. класса
    def __init__(  # pylint: disable=super-init-not-called
        self, running_speed: float
    ) -> None:
        """Initialize flightless bird with running speed."""
        # таким образом, у нас остается только один атрибут
        self.running_speed = running_speed

    # кроме того, результатом метода .move() будет 'Running'
    def move(self) -> None:
        """Make flightless bird run."""
        print("Running")

In [357]:
# создадим объект ostrich класса Flightless
ostrich = Flightless(60)

In [358]:
# посмотрим на значение атрбута скорости
print(ostrich.running_speed)

60


In [359]:
# и проверим метод .move()
ostrich.move()

Running


In [360]:
# подкласс Flightless сохранил методы всех родительских классов
ostrich.eat()

Eating


Множественное наследование

In [361]:
# создадим родительский класс Fish


class Fish:
    """Base class for fish that can swim."""

    # и метод .swim()
    def swim(self) -> None:
        """Make fish swim."""
        print("Swimming")

In [362]:
# и еще один родительский класс Bird


class Bird2:
    """Base class for birds that can fly."""

    # и метод .fly()
    def fly(self) -> None:
        """Make bird fly."""
        print("Flying")

In [363]:
# теперь создадим класс-потомок этих двух классов


class SwimmingBird(Bird2, Fish):
    """A bird that can both swim and fly."""

    pass  # pylint: disable=unnecessary-pass

In [364]:
# создадим объект duck класса SwimmingBird
duck = SwimmingBird()

In [365]:
# как мы видим утка умеет как летать,
duck.fly()

Flying


In [366]:
# так и плавать
duck.swim()

Swimming


#### Полиморфизм

In [367]:
# для чисел '+' является оператором сложения
print(2 + 2)

4


In [368]:
# для строк - оператором объединения
print("классы" + " и " + "объекты")

классы и объекты


1. Полиморфизм функций

In [369]:
# функцию len() можно применить к строке
len("Программирование на Питоне")

26

In [370]:
# кроме того, она способна работать со списком
len(["Программирование", "на", "Питоне"])

3

In [371]:
# словарем
len({0: "Программирование", 1: "на", 2: "Питоне"})

3

In [372]:
len(np.array([1, 2, 3]))

3

2. Полиморфизм классов

Создадим объекты с одинаковыми атрибутами и методами

In [373]:
# создадим класс котов


class CatClass6:
    """Class representing a cat with name, type and color attributes."""

    # определим атрибуты клички, типа и цвета шерсти
    def __init__(self, name: str, color: str) -> None:
        """Initialize a cat with given name and color."""
        self.name = name
        self._type_ = "кот"
        self.color = color

    # создадим метод .info() для вывода этих атрибутов
    def info(self) -> None:
        """Print information about the cat."""
        print(f"Меня зовут {self.name}, я {self._type_}")
        print(f"цвет моей шерсти {self.color}")

    # и метод .sound(), показывающий, что коты умеют мяукать
    def sound(self) -> None:
        """Print the sound a cat makes."""
        print("Я умею мяукать")

In [374]:
# создадим класс собак


class DogClass:
    """Class representing a dog with name, type and color attributes."""

    # с такими же атрибутами
    def __init__(self, name: str, color: str) -> None:
        """Initialize a dog with given name and color."""
        self.name = name
        self._type_ = "пес"
        self.color = color

    # и методами
    def info(self) -> None:
        """Print information about the dog."""
        print(f"Меня зовут {self.name}, я {self._type_}")
        print(f"цвет моей шерсти {self.color}")

    # хотя, обратите внимание, действия внутри методов отличаются
    def sound(self) -> None:
        """Print the sound a dog makes."""
        print("Я умею лаять")

Создадим объекты этих классов

In [375]:
cat = CatClass6("Бегемот", "черный")
dog = DogClass("Барбос", "серый")

В цикле `for` вызовем атрибуты и методы каждого из классов

In [376]:
for animal in (cat, dog):
    animal.info()
    animal.sound()
    print()

Меня зовут Бегемот, я кот
цвет моей шерсти черный
Я умею мяукать

Меня зовут Барбос, я пес
цвет моей шерсти серый
Я умею лаять



### Парадигмы программирования

In [377]:
patients: list[dict[str, str | int]] = [
    {"name": "Николай", "height": 178},
    {"name": "Иван", "height": 182},
    {"name": "Алексей", "height": 190},
]

#### Процедурное программирование

In [378]:
# создадим переменные для общего роста и количества пациентов
total, count = 0, 0

# в цикле for пройдемся по пациентам (отдельным словарям)
for patient in patients:
    # достанем значение роста и прибавим к текущему значению переменной total
    total += int(patient["height"])
    # на каждой итерации будем увеличивать счетчик пациентов на один
    count += 1

# разделим общий рост на количество пациентов,
# чтобы получить среднее значение
print(total / count)

183.33333333333334


#### Объектно-ориентированное программирование

In [379]:
# создадим класс для работы с данными DataClass


class DataClass:
    """Class for calculating statistics on data."""

    # при создании объекта будем передавать ему данные для анализа
    def __init__(self, data: list[dict[str, str | int]]) -> None:
        """Initialize with data for analysis."""
        self.data = data
        self.metric = ""
        self.__total = 0
        self.__count = 0

    # кроме того, создадим метод для расчета среднего значения
    def count_average(self, metric: str) -> float:
        """Calculate average value for given metric."""
        # параметр metric определит, по какому столбцу считать среднее
        self.metric = metric

        # объявим два частных атрибута
        self.__total = 0
        self.__count = 0

        # в цикле for пройдемся по списку словарей
        for item in self.data:

            # рассчитем общую сумму по указанному в metric
            # значению каждого словаря
            self.__total += int(item[self.metric])

            # и количество таких записей
            self.__count += 1

        # разделим общую сумму показателя на количество записей
        return self.__total / self.__count

In [380]:
# создадим объект класса DataClass и передадим ему данные о пациентах
data_object = DataClass(patients)

# вызовем метод .count_average() с метрикой 'height'
data_object.count_average("height")

183.33333333333334

#### Функциональное программирование

Функция map()

In [381]:
# lambda-функция достанет значение по ключу height
# функция map() применит lambda-функцию к каждому вложенному в patients словарю
# функция list() преобразует результат в список
heights = list(map(lambda x: int(x["height"]), patients))
print(heights)

[178, 182, 190]


In [382]:
# воспользуемся функциями sum() и len() для нахождения среднего значения
print(sum(heights) / len(heights))

183.33333333333334


Функция einsum()

In [383]:
# возьмем два двумерных массива
a_val = np.array([[0, 1, 2], [3, 4, 5]])

b_val = np.array([[5, 4], [3, 2], [1, 0]])

In [384]:
# перемножим a и b по индексу j через функцию np.einsum()
np.einsum("ij, jk -> ik", a_val, b_val)

array([[ 5,  2],
       [32, 20]])

### Классы и объекты в машинном обучении

#### Готовые классы в библиотеке sklearn

In [385]:
# возьмем данные роста и обхвата шеи
x_val_ar = np.array(
    [
        1.48,
        1.49,
        1.49,
        1.50,
        1.51,
        1.52,
        1.52,
        1.53,
        1.53,
        1.54,
        1.55,
        1.56,
        1.57,
        1.57,
        1.58,
        1.58,
        1.59,
        1.60,
        1.61,
        1.62,
        1.63,
        1.64,
        1.65,
        1.65,
        1.66,
        1.67,
        1.67,
        1.68,
        1.68,
        1.69,
        1.70,
        1.70,
        1.71,
        1.71,
        1.71,
        1.74,
        1.75,
        1.76,
        1.77,
        1.77,
        1.78,
    ]
)
y_val_ar = np.array(
    [
        29.1,
        30.0,
        30.1,
        30.2,
        30.4,
        30.6,
        30.8,
        30.9,
        31.0,
        30.6,
        30.7,
        30.9,
        31.0,
        31.2,
        31.3,
        32.0,
        31.4,
        31.9,
        32.4,
        32.8,
        32.8,
        33.3,
        33.6,
        33.0,
        33.9,
        33.8,
        35.0,
        34.5,
        34.7,
        34.6,
        34.2,
        34.8,
        35.5,
        36.0,
        36.2,
        36.3,
        36.6,
        36.8,
        36.8,
        37.0,
        38.5,
    ]
)

In [386]:
# преобразуем данные роста в двумерный массив
X_2D = x_val_ar.reshape(-1, 1)
print(X_2D)

[[1.48]
 [1.49]
 [1.49]
 [1.5 ]
 [1.51]
 [1.52]
 [1.52]
 [1.53]
 [1.53]
 [1.54]
 [1.55]
 [1.56]
 [1.57]
 [1.57]
 [1.58]
 [1.58]
 [1.59]
 [1.6 ]
 [1.61]
 [1.62]
 [1.63]
 [1.64]
 [1.65]
 [1.65]
 [1.66]
 [1.67]
 [1.67]
 [1.68]
 [1.68]
 [1.69]
 [1.7 ]
 [1.7 ]
 [1.71]
 [1.71]
 [1.71]
 [1.74]
 [1.75]
 [1.76]
 [1.77]
 [1.77]
 [1.78]]


In [387]:
# создадим объект этого класса и запишем в переменную model
model = LinearRegression()

# обучим модель с помощью метода .fit(), которому передадим наши данные
model.fit(X_2D, y_val_ar)

# на выходе получим коэффициенты линейной регрессии
print(model.coef_, model.intercept_)

[26.86181201] -10.570936299787334


In [388]:
# построим прогноз и выведем первые пять значений
y_pred = model.predict(X_2D)
print(y_pred[:5])

[29.18454547 29.45316359 29.45316359 29.72178171 29.99039983]


#### Пример ООП: собственный класс линейной регрессии

In [389]:
# создадим класс SimpleLinearRegression


class SimpleLinearRegression:
    """Simple implementation of linear regression."""

    # в методе .__init__() объявим переменные наклона и сдвига
    def __init__(self) -> None:
        """Initialize model coefficients."""
        self.slope_ = 0.0
        self.intercept_ = 0.0

    # создадим метод .fit()
    def fit(self, x_val, y_val) -> None:  # type: ignore
        """Fit linear regression model."""
        # найдем среднее значение X и y
        x_mean = self.find_mean(x_val)
        y_mean = self.find_mean(y_val)

        # объявим переменные для числителя и знаменателя
        numerator, denominator = 0, 0

        # в цикле пройдемся по данным
        for index, x_el in enumerate(x_val):
            y_el = y_val[index]

            # вычислим значения числителя и знаменателя по формуле выше
            numerator += (x_el - x_mean) * (y_el - y_mean)
            denominator += (x_el - x_mean) ** 2

        # найдем наклон и сдвиг
        slope_ = numerator / denominator
        intercept_ = y_mean - slope_ * x_mean

        # сохраним получившиеся коэффициенты в виде атрибутов
        self.slope_ = slope_
        self.intercept_ = intercept_

    # метод .predict() просто умножит через скалярное произведение
    # вектор данных на наклон и прибавит сдвиг
    def predict(self, x_val: np.ndarray):  # type: ignore
        """Make predictions using fitted model."""
        # на выходе мы получим вектор прогнозных значений
        return np.dot(self.slope_, x_val) + self.intercept_

    # служебный метод: расчет среднего
    def find_mean(self, nums: np.ndarray):  # type: ignore
        """Calculate mean of input numbers."""
        return sum(nums) / len(nums)

In [390]:
# создадим объект класса SimpleLinearRegression
model = SimpleLinearRegression()

In [391]:
# применим метод .fit()
model.fit(x_val_ar, y_val_ar)

# посмотрим на коэффициенты
print(model.slope_, model.intercept_)

26.861812005569757 -10.570936299787334


In [392]:
# сделаем прогноз через .predict()
y_pred = model.predict(x_val_ar)

# и выведем первые пять коэффициентов
print(y_pred[:5])

[29.18454547 29.45316359 29.45316359 29.72178171 29.99039983]
